In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/heart-failure-prediction/heart.csv

In [2]:
import pandas as pd

In [3]:
df = pd.read_csv("/kaggle/input/heart-failure-prediction/heart.csv")
df.head()

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
0,40,M,ATA,140,289,0,Normal,172,N,0.0,Up,0
1,49,F,NAP,160,180,0,Normal,156,N,1.0,Flat,1
2,37,M,ATA,130,283,0,ST,98,N,0.0,Up,0
3,48,F,ASY,138,214,0,Normal,108,Y,1.5,Flat,1
4,54,M,NAP,150,195,0,Normal,122,N,0.0,Up,0

In [4]:
df.describe()

,Age,RestingBP,Cholesterol,FastingBS,MaxHR,Oldpeak,HeartDisease
count,918.000000,918.000000,918.000000,918.000000,918.000000,918.000000,918.000000
mean,53.510893,132.396514,198.799564,0.233115,136.809368,0.887364,0.553377
std,9.432617,18.514154,109.384145,0.423046,25.460334,1.066570,0.497414
min,28.000000,0.000000,0.000000,0.000000,60.000000,-2.600000,0.000000
25%,47.000000,120.000000,173.250000,0.000000,120.000000,0.000000,0.000000
50%,54.000000,130.000000,223.000000,0.000000,138.000000,0.600000,1.000000
75%,60.000000,140.000000,267.000000,0.000000,156.000000,1.500000,1.000000
max,77.000000,200.000000,603.000000,1.000000,202.000000,6.200000,1.000000

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 918 entries, 0 to 917
Data columns (total 12 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Age             918 non-null    int64
 1   Sex             918 non-null    object
 2   ChestPainType   918 non-null    object
 3   RestingBP       918 non-null    int64
 4   Cholesterol     918 non-null    int64
 5   FastingBS       918 non-null    int64
 6   RestingECG      918 non-null    object
 7   MaxHR           918 non-null    int64
 8   ExerciseAngina  918 non-null    object
 9   Oldpeak         918 non-null    float64
 10  ST_Slope        918 non-null    object
 11  HeartDisease    918 non-null    int64
dtypes: float64(1), int64(6), object(5)
memory usage: 86.2+ KB

In [6]:
df["Age"].isnull().sum()

0

In [7]:
df["Sex"].isna().sum()

0

In [8]:
df["Sex"].value_counts()[0]+df["Sex"].value_counts()[1]

918

In [9]:
df.drop_duplicates(inplace=True)

In [10]:
new_df=df

In [11]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
le.fit(new_df["Sex"])

LabelEncoder()

In [12]:
le.classes_

array(['F', 'M'], dtype=object)

In [13]:
new_df["encode_sex"]=le.fit_transform(new_df["Sex"])

In [14]:
new_df.drop("Sex",axis=1,inplace=True)
new_df

,Age,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease,encode_sex
0,40,ATA,140,289,0,Normal,172,N,0.0,Up,0,1
1,49,NAP,160,180,0,Normal,156,N,1.0,Flat,1,0
2,37,ATA,130,283,0,ST,98,N,0.0,Up,0,1
3,48,ASY,138,214,0,Normal,108,Y,1.5,Flat,1,0
4,54,NAP,150,195,0,Normal,122,N,0.0,Up,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...
913,45,TA,110,264,0,Normal,132,N,1.2,Flat,1,1
914,68,ASY,144,193,1,Normal,141,N,3.4,Flat,1,1
915,57,ASY,130,131,0,Normal,115,Y,1.2,Flat,1,1
916,57,ATA,130,236,0,LVH,174,N,0.0,Flat,1,0
917,38,NAP,138,175,0,Normal,173,N,0.0,Up,0,1

In [15]:
d=new_df
d

,Age,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease,encode_sex
0,40,ATA,140,289,0,Normal,172,N,0.0,Up,0,1
1,49,NAP,160,180,0,Normal,156,N,1.0,Flat,1,0
2,37,ATA,130,283,0,ST,98,N,0.0,Up,0,1
3,48,ASY,138,214,0,Normal,108,Y,1.5,Flat,1,0
4,54,NAP,150,195,0,Normal,122,N,0.0,Up,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...
913,45,TA,110,264,0,Normal,132,N,1.2,Flat,1,1
914,68,ASY,144,193,1,Normal,141,N,3.4,Flat,1,1
915,57,ASY,130,131,0,Normal,115,Y,1.2,Flat,1,1
916,57,ATA,130,236,0,LVH,174,N,0.0,Flat,1,0
917,38,NAP,138,175,0,Normal,173,N,0.0,Up,0,1

In [16]:
le.fit(d["ChestPainType"])
le.classes_
d["encode_ChestPainType"]=le.fit_transform(d["ChestPainType"])
d.drop("ChestPainType",axis=1,inplace=True)

In [17]:
le.fit(d["ST_Slope"])
le.classes_
d["encode_ST_Slope"]=le.fit_transform(d["ST_Slope"])
d.drop("ST_Slope",axis=1,inplace=True)

In [18]:
d

,Age,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,HeartDisease,encode_sex,encode_ChestPainType,encode_ST_Slope
0,40,140,289,0,Normal,172,N,0.0,0,1,1,2
1,49,160,180,0,Normal,156,N,1.0,1,0,2,1
2,37,130,283,0,ST,98,N,0.0,0,1,1,2
3,48,138,214,0,Normal,108,Y,1.5,1,0,0,1
4,54,150,195,0,Normal,122,N,0.0,0,1,2,2
...,...,...,...,...,...,...,...,...,...,...,...,...
913,45,110,264,0,Normal,132,N,1.2,1,1,3,1
914,68,144,193,1,Normal,141,N,3.4,1,1,0,1
915,57,130,131,0,Normal,115,Y,1.2,1,1,0,1
916,57,130,236,0,LVH,174,N,0.0,1,0,1,1
917,38,138,175,0,Normal,173,N,0.0,0,1,2,2

In [19]:
le.fit(d["ExerciseAngina"])
le.classes_
d["encode_ExerciseAngina"]=le.fit_transform(d["ExerciseAngina"])
d.drop("ExerciseAngina",axis=1,inplace=True)
d

,Age,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,Oldpeak,HeartDisease,encode_sex,encode_ChestPainType,encode_ST_Slope,encode_ExerciseAngina
0,40,140,289,0,Normal,172,0.0,0,1,1,2,0
1,49,160,180,0,Normal,156,1.0,1,0,2,1,0
2,37,130,283,0,ST,98,0.0,0,1,1,2,0
3,48,138,214,0,Normal,108,1.5,1,0,0,1,1
4,54,150,195,0,Normal,122,0.0,0,1,2,2,0
...,...,...,...,...,...,...,...,...,...,...,...,...
913,45,110,264,0,Normal,132,1.2,1,1,3,1,0
914,68,144,193,1,Normal,141,3.4,1,1,0,1,0
915,57,130,131,0,Normal,115,1.2,1,1,0,1,1
916,57,130,236,0,LVH,174,0.0,1,0,1,1,0
917,38,138,175,0,Normal,173,0.0,0,1,2,2,0